server:
  port: 8123

spring:
  application:
    name: frame-platform
  datasource:
    name: report-ds
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/heitu?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  data:
    mongodb:
      database: heitu
      uri: mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
      print: true  #是否打印查询语句
      slowQuery: true  #是否记录慢查询到数据库中
      slowTime: 1000 #慢查询最短时间,默认为1000毫秒
  rabbitmq:
    host: 127.0.0.1  #虚拟机的ip地址
    port: 5672 #端口号
    username: guest  #用户名
    password: guest  #密码
    publisher-confirm-type: correlated
    publisher-returns: true
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, shutdown
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
swagger:
  enabled: true

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.wwj.common.enums

secure:
  ignored:
    urls: #安全路径白名单
      - /doc.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /sysAdmin/login
      - /error
      - /home/**
      - /see/**
jwt:
  secret: DEV62628816  #服务端私钥（一定不能泄露）
  expiration: 8640000   #过期时间 60*60*24  =一天
  tokenHead: Bearer #jwt规范  #告诉客户端jwt令牌开头需要加的一个字符串
  tokenHeader: Authorization #告诉客户端你要在请求头里面传什么参数名字

file:
  upload:
    #path: /home/httech/app/dmyl/dmyl-platform/upload/
    path: D:\\upload\\upload\\